var arr=['Pink','Red','Brown']
document.write(`${arr} <br>`)
arr.unshift(prompt('Enter any color to be added in the beginning'))
document.write(`${arr} <br>`)
arr.push(prompt('Enter any color to be added in the end'))
document.write(`${arr} <br>`)
arr.unshift(prompt('Enter any color to be added in the beginning'),prompt('Enter any color to be added in the beginning'))
document.write(`${arr} <br>`)
arr.shift()
document.write(`${arr} <br>`)
arr.pop()
document.write(`${arr} <br>`)
arr.splice(+prompt('Enter desired index where you want color to be added'),0,prompt('Enter any color to be added at the desired index'))
document.write(`${arr} <br>`)
arr.splice(+prompt('Enter desired index where you want colors to be deleted'),+prompt('How many colors you want to delete'))
document.write(`${arr} <br>`)